### ISSUE TITLE
Add "principal-local-authority" IDs

### ISSUE THREAD

**Issue by symroe** [ajparsons/uk_local_authority_names_and_codes#1]
GDS have renamed `local-authority-wls` to `principal-local-authority` in the map file, but kept the register name the same (`local-authority-wls`). 
 
https://github.com/openregister/local-authority-data/pull/31

This is confusing, but also breaks mappings in this document. 

I think the best thing to do is to add both the "principal-local-authority" and "local-authority-wls" in this mapping, as that saves applications renaming between the two.

**Comment by ajparsons** [comment]
Okay, looking at that and the rationale I'm thinking of creating an old-register and old-register-and-code column to account for this change and allow other registers to go their own way. (Ideally there would be a permanent unique-id in the register of registers? but the non-english ones aren't offical offical yet are they?)
