### ISSUE TITLE
Latitude/longitude switched around

### ISSUE THREAD

**Issue by slowe** [ajparsons/uk_local_authority_names_and_codes#15]
I stumbled across the `uk_local_authorities.csv` file via the [My Society Data page](https://data.mysociety.org/datasets/uk-local-authority-names-and-codes/). I'm not sure if you are still maintaining this file or not but I noticed that the latitudes and longitudes appear to be the wrong way around.

**Comment by ajparsons** [comment]
Hello! I fixed this issue when I was setting up the new version of the repo at https://github.com/mysociety/uk_local_authority_names_and_codes/blob/main/data/uk_local_authorities.csv

I'll update the reference in the data page so it goes to the right page.
