### ISSUE TITLE
Inconsistent capitalisation of "Unitary authority"

### ISSUE THREAD

**Issue by chrismytton** [ajparsons/uk_local_authority_names_and_codes#3]
In the `local-authority-type-name` column of `uk_local_authorities.csv` most entries for unitary authorities have the value "Unitary authority", but the new row for Buckinghamshire, added in https://github.com/ajparsons/uk_local_authority_names_and_codes/commit/1c1cc5f11a5b9fef28a808cfefe522c0a80f18a6, has the value "Unitary Authority".

Would it be possible to make these consistent? My use case is I want to show a list of filters for local authority types and I'm generating that list from the unique values in the `local-authority-type-name` column.

Thanks for this excellent resource by the way, super handy! 🥇

**Comment by ajparsons** [comment]
Should be done!
